name: Azure AD Group Based Workflow

on:
  workflow_dispatch:

jobs:
  check-github-user-email-in-ad-group:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Triggering User Email
      id: get-user-email
      run: |
        # Retrieve the email address associated with the authenticated GitHub user
        EMAIL=$(# GitHub CLI api
        # https://cli.github.com/manual/gh_api

        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /user/emails)
        echo "GitHub API Response:"
        echo "$EMAIL"
        
        # Extract primary email using jq
        PRIMARY_EMAIL=$(echo "$EMAIL" | jq -r '.[] | select(.primary == true) | .email')
        echo "Primary Email Address:"
        echo "$PRIMARY_EMAIL"
        
        # Set the primary email as an output
        echo "email=$PRIMARY_EMAIL" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} 

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}
    
    - name: Retrieve Azure AD Object ID for Email
      id: get-user-object-id
      run: |
        # Retrieve the object ID associated with the email address
        # Run the Azure CLI command and capture the output
        $userInfo = az ad user show --id "${{ env.email }}"

        # Convert the output to JSON
        $userJson = $userInfo | ConvertFrom-Json

        # Extract the user's ID
        $userId = $userJson.id

        echo "object_id=$userId" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        AZURE_CREDENTIALS: ${{ secrets.AZURECREDENTIALS }}  
      shell: pwsh

    - name: Check Azure AD Group Membership
      id: check-group
      run: |
        # Check group membership using the obtained object ID
        az ad group member check --group 'AD-SEC-ALL-GLO-EOON-DEVELOPERS' --member-id "${{ env.object_id }}"
        
    - name: Execute Workflow based on Group Membership
      if: steps.check-group.outputs == 'true'
      run: |
        # Your workflow commands here
        echo "GitHub user's email is a member of the specified Azure AD group, proceeding with workflow execution."
     
