name: Azure AD Group Based Workflow

on:
  workflow_dispatch:

jobs:
  check-github-user-email-in-ad-group:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Triggering User Info
      id: get-user
      run: |
        EMAIL=$(curl -s -H "Authorization: Bearer ${{ secrets.TOKEN}}" https://api.github.com/user/emails | jq -r '.[] | select(.primary == true).email')
        echo "::set-output name=email::$EMAIL"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}
    
    - name: Retrieve Azure AD Object ID for Email
      id: get-user-object-id
      run: |
        # Retrieve the object ID associated with the email address
        OBJECT_ID=$(az ad user show --id "${{ steps.get-user-email.outputs.email }}" --query objectId -o tsv)
        echo "object_id=$OBJECT_ID" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        AZURE_CREDENTIALS: ${{ secrets.AZURECREDENTIALS }}  

    - name: Check Azure AD Group Membership
      id: check-group
      run: |
        # Query Azure AD to verify if the email address is a member of the group
        # Replace 'group_name' with the name of your Azure AD group
        az ad group member check --group 'AD-SEC-ALL-GLO-EOON-DEVELOPERS' --member-id "${{ env.object_id }}"
        
    - name: Execute Workflow based on Group Membership
      if: steps.check-group.outputs == 'true'
      run: |
        # Your workflow commands here
        echo "GitHub user's email is a member of the specified Azure AD group, proceeding with workflow execution."
        else
        echo "GitHub user's email is not a member of the specified Azure AD group, skipping workflow execution."

    - name: Execute Workflow based on Group Membership
      if: steps.check-group.outputs == 'false'
      run: |
        echo "GitHub user's email is not a member of the specified Azure AD group, skipping workflow execution."
