name: download secrets keyvault

on:
  workflow_dispatch:
    
    jobs:
      download_secrets:
        runs-on: ubuntu-latest

        steps:

          - name: Log in Azure
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURECREDENTIALS }}

          - name: download secrets from keyvault
            uses: Azure/get-keyvault-secrets@v1
            with:
              keyvault: "SPNKeyVault02 "
              secrets: 'Client-Secret, Client-ID'
            id: myGetSecretAction

          - name: show downloaded secrets
            run: |
              echo ${{steps.myGetSecretAction.outputs.Client-Secret}}
              echo ${{steps.myGetSecretAction.outputs.Client-ID}}
    
